#!/bin/sh

TAB="$(printf '\t')"

cat <<EOF
<!DOCTYPE html>
<html lang="cs">
	<head>
		<meta charset="UTF-8">  
		<title>Špajza</title>
		<style>
			body {
				text-align: center;
				background-color: white;
			}
			.rovnac > img {
				display: inline-block;
				max-width: 300px;
			}
		</style>
	</head>

	<body>
		<h1><b>Špajza</b></h1>
<!--		<h2><a href="https://sklad.rohlik.sk">späť</a></h2> -->
		<hr>

		<table style="width:100%">
EOF

i=0
SUM=0
NAME=""
IFS=""
line=""
grep -v '^$' | while [[ "$line" != "END" ]] ; do
	read -r line || line="END"
	if echo "$line" | grep -q -v "^$TAB" ; then
		if [[ "$NAME" ]] ; then
			if [[ "EAN" != "0" && -n "$URL" && ! -f "$EAN.png" ]] ; then
				IMGURL=$(curl -s "$URL" | grep cdn-cgi | tr ">" "\n" | grep cdn-cgi | head -n1 | sed -e 's/^.*"[^"]*cdn-cgi[^"]*\(https[^"]*\)".*$/\1/g')
				echo "$IMGURL" | grep -q "^https" || IMGURL=
			else
				IMGURL=
			fi
			if [[ -n "$IMGURL" ]] ; then
				TMPFILE=$(mktemp)
				curl -s "$IMGURL" --output "$TMPFILE"
				convert "$TMPFILE" -resize 150x150 "$EAN.png"
				rm -f "$TMPFILE"
			fi

			printf "%s|%s|%s\n" "$EAN" "$NAME" "$SUM"

			SUM=0
		fi
		
		if echo "$line" | grep -q "$TAB" ; then
			EAN=$(echo "$line" | awk -F"$TAB" '{print $1}')
			NAME=$(echo "$line" | awk -F"$TAB" '{print $2}')
			URL=$(echo "$line" | awk -F"$TAB" '{print $3}')
		else
			EAN=0
			NAME="$line"
			URL=""
		fi
	else
		COUNT=$(echo "$line" | awk '{print $2}')
		SUM=$((SUM + COUNT))
	fi
done | LC_COLLATE=sk_SK.UTF-8 sort -t"|" -k2,2 | while read line ; do
	EAN=$(echo "$line" | awk -F"|" '{print $1}')
	NAME=$(echo "$line" | awk -F"|" '{print $2}')
	SUM=$(echo "$line" | awk -F"|" '{print $3}')

	if ((i == 5)) ; then
		printf "\t\t\t</tr>\n"
		i=0
	fi
	if ((i == 0)) ; then
		printf "\t\t\t<tr>\n"
	fi
	cat <<EOF
				<th>
					<img src="$EAN.png" alt="chýba obrázok"><br>
					$NAME<br>
					$SUM ks
				</th>
EOF
	i=$((i + 1))
done

((i > 0)) && printf "\t\t\t</tr>\n"

cat <<EOF
		</table>
	</body>
</html>
EOF
