#!/bin/sh

CATFILE=$1
CATEGORY=$2

TAB="$(printf '\t')"

CATNAME="Všetko"
if [[ -f "$CATFILE" && "$CATEGORY" ]] ; then
	cat "$CATFILE" | while read line ; do
		ID=$(echo "$line" | awk -F"$TAB" '{print $1}')
		NAME=$(echo "$line" | awk -F"$TAB" '{print $2}')
		if [[ "$CATEGORY" == "$ID" ]] ; then
			CATNAME="$NAME"
			break
		fi
	done
fi

cat <<EOF
<!DOCTYPE html>
<html lang="cs">
	<head>
		<meta charset="UTF-8">  
		<title>Špajza ($CATNAME)</title>
		<style>
			body {
				text-align: center;
				background-color: white;
			}
			.rovnac > img {
				display: inline-block;
				max-width: 300px;
			}
		</style>
	</head>

	<body>
		<h1><b>Špajza ($CATNAME)</b></h1>
		<hr>
		<table style="width:100%">
			<tr>
				<th><a href=".">Všetko</a></th>
EOF
if [[ -f "$CATFILE" ]] ; then
	i=1
	cat "$CATFILE" | while read line ; do
		ID=$(echo "$line" | awk -F"$TAB" '{print $1}')
		NAME=$(echo "$line" | awk -F"$TAB" '{print $2}')
		printf "\t\t\t\t<th><a href="%s.html">%s</a></th>\n" "$ID" "$NAME"

		i=$((i + 1))

		if ((i == 5)) ; then
			printf "\t\t\t</tr>\n\t\t\t</tr>\n"
			i=0
		fi
	done
fi
cat <<EOF
			</tr>
		</table>
		<hr>

		<table style="width:100%">
EOF

i=0
NAME=""
IFS=""
END=0
EMPTY=0
while ((END == 0)) ; do
	if read -r ORIGLINE ; then
		# strip comments
		line=${ORIGLINE%%#*}
		# strip trailing whitespaces
		while
			TAIL=${line:${#line} - 1}
			[[ "$TAIL" == " " || "$TAIL" == "$TAB" ]]
		do
			line=${line:0:${#line} - 1}
		done
	else
		line=""
		END=1
	fi

	if echo "$line" | grep -q -v "^$TAB" ; then
		if [[ "$NAME" ]] ; then
			if [[ -n "$URL" && ! -f "$EAN.png" ]] ; then
				IMGURL=$(curl -s "$URL" | grep cdn-cgi | tr ">" "\n" | grep cdn-cgi | head -n1 | sed -e 's/^.*"[^"]*cdn-cgi[^"]*\(https[^"]*\)".*$/\1/g')
				echo "$IMGURL" | grep -q "^https" || IMGURL=
			else
				IMGURL=
			fi
			if [[ -n "$IMGURL" ]] ; then
				TMPFILE=$(mktemp)
				curl -s "$IMGURL" --output "$TMPFILE"
				convert "$TMPFILE" -resize 150x150 "$EAN.png"
				rm -f "$TMPFILE"
			fi

			KEY=$((SUM != 0))
			[[ -z "$CATEGORY" || "$CATEGORY" == "$CAT" ]] && printf "%s|%s|%s|%s|%s\n" "$EAN" "$NAME" "$SUM" "$URL" "$KEY"
		fi
		
		EAN=$(echo "$line" | awk -F"$TAB" '{print $1}')
		NAME=$(echo "$line" | awk -F"$TAB" '{print $2}')
		URL=$(echo "$line" | awk -F"$TAB" '{print $3}')
		CAT=$(echo "$line" | awk -F"$TAB" '{print $4}')

		SUM=0
	else
		COUNT=$(echo "$line" | awk '{print $2}')
		SUM=$((SUM + COUNT))
	fi
done | LC_COLLATE=sk_SK.UTF-8 sort -t"|" -k5nr,5 -k2,2 | while read line ; do
	EAN=$(echo "$line" | awk -F"|" '{print $1}')
	NAME=$(echo "$line" | awk -F"|" '{print $2}')
	SUM=$(echo "$line" | awk -F"|" '{print $3}')
	URL=$(echo "$line" | awk -F"|" '{print $4}')

	if ((SUM == 0 && EMPTY == 0)) ; then
		EMPTY=1
		i=0

		printf '\t\t\t</tr>\n\t\t</table>\n\t\t<hr>\n\t\t<table style="width:100%%">\n'
	fi

	A1=
	A2=
	if [[ "$URL" ]] ; then
		A1="<a rel=\"noreferrer\" href=\"$URL\">"
		A2="</a>"
	fi

	if ((i == 5)) ; then
		printf "\t\t\t</tr>\n"
		i=0
	fi
	if ((i == 0)) ; then
		printf "\t\t\t<tr>\n"
	fi
	cat <<EOF
				<th>
					<img src="$EAN.png" alt="chýba obrázok"><br>
					$A1$NAME$A2<br>
					$SUM ks
				</th>
EOF
	[[ ! -f "$EAN.png" ]] && echo "WARNING: Missing picture $EAN.png" > /dev/stderr
	i=$((i + 1))
done

((i > 0)) && printf "\t\t\t</tr>\n"

cat <<EOF
		</table>
	</body>
</html>
EOF
